[build]
  base = "client"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://dashboard-analytics-backend.herokuapp.com/api"
  REACT_APP_SOCKET_URL = "https://dashboard-analytics-backend.herokuapp.com"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers básicos de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
